### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.index#8]
This package is not yet compatible with Python 3.6, see https://travis-ci.org/zopefoundation/zopetoolkit/jobs/173487024#1333

**Comment by mgedmin** [comment]
Test log consists of many (11) repetitions of this error:
```
Traceback (most recent call last):
  File "/opt/python/3.6-dev/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python/3.6-dev/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.index-4.2.0-py3.6-linux-x86_64.egg/zope/index/text/tests/test_htmlsplitter.py", line 36, in test_class_conforms_to_ISplitter
    verifyClass(ISplitter, self._getTargetClass())
  File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.index-4.2.0-py3.6-linux-x86_64.egg/zope/index/text/tests/test_htmlsplitter.py", line 27, in _getTargetClass
    from zope.index.text.htmlsplitter import HTMLWordSplitter
  File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.index-4.2.0-py3.6-linux-x86_64.egg/zope/index/text/htmlsplitter.py", line 23, in <module>
    WORDS = re.compile(r"(?L)\w+")
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/sre_parse.py", line 866, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
```

**Comment by mgedmin** [comment]
The [offending code line](https://github.com/zopefoundation/zope.index/blob/dc4bb06ce228dc0079497eded75f64f27fc69ae5/src/zope/index/text/htmlsplitter.py#L23-L24) is:

```python
WORDS = re.compile(r"(?L)\w+")
GLOBS = re.compile(r"(?L)\w+[\w*?]*")
```

Now I don't know whether this regex is intended to handle Unicode or byte strings (and also whether that changes depending on which Python version you use), so I don't know whether the correct thing to do is to remove the `(?L)` flag, or change the regex string to be a bytestring, or do so depending on Python version, or what.

**Comment by jamadden** [comment]
The interface documentation uses the word "text" and "text" is the name of the package. Typically in zope packages that means unicode strings. 

However, [the test case](https://github.com/zopefoundation/zope.index/blob/master/src/zope/index/text/tests/test_htmlsplitter.py) simply passes native strings---bytes on Py2, text/unicode on Py3. The tests do [change the locale](https://github.com/zopefoundation/zope.index/blob/master/src/zope/index/text/tests/test_htmlsplitter.py#L51) and assert that things happen...BUT, [the docs for re.LOCALE](https://docs.python.org/3/library/re.html#re.LOCALE) state that (emphasis mine):

> Make \w, \W, \b, \B, \s and \S dependent on the current locale. **The use of this flag is discouraged** as the locale mechanism is very unreliable, and it only handles one “culture” at a time anyway; **you should use Unicode matching instead, which is the default in Python 3 for Unicode (str) patterns**. This flag can be used only with bytes patterns.

So I suspect that on Python 3, we don't want the `(?L)` flag at all.
